### ISSUE TITLE
imdb data is available for download, any hope for a `imdb-cli` of sorts?

### ISSUE THREAD

**Issue by haakonstorm** [BurntSushi/goim#11]
`https://datasets.imdbws.com/`

**Comment by BurntSushi** [comment]
I don't know what you're asking.

**Comment by haakonstorm** [comment]
Sorry I was unclear.
I was looking for a command line tool to interface with imdb, and was super happy to come across `goim` and to see the  `rg` dev behind it, which we all use and love.
The readme clearly states "PROJECT WILL BE OBSOLETE SEPTEMBER 10, 2017" and reason given imdb's data dumps are deprecated/changed.
I read up on the current state of imdb and found the new dumps, as linked. Since this repo hasn't been updated for a long time, I thought you might've been unaware of the new location of the dumps. 
A `imdb-cli` tool of sorts to interface with imdb would be awesome.

**Comment by BurntSushi** [comment]
I'm aware and I built a new tool that uses the new dumps: https://github.com/BurntSushi/imdb-rename

This `goim` project was built around the old dumps and uses a relational database to store and search the data. The new tool is built around the new dumps and uses a bespoke inverted index database for searching.

> A `imdb-cli` tool of sorts to interface with imdb would be awesome.

To be clear, I don't accept requests to build tools. I build tools that I want to build.

**Comment by BurntSushi** [comment]
And see also: https://github.com/BurntSushi/goim/issues/10
