### ISSUE TITLE
Support Actor Image URL

### ISSUE THREAD

**Issue by luzer** [BurntSushi/goim#8]
hi
was wondering if you had plan to support URLs of an actor bio, in IMDB.

love your work- using it here - http://www.tableaumeaway.com/seinfeld-sentiment-analysis-tableau-v10/

**Comment by BurntSushi** [comment]
Neat project!

Whether it's supportable or not is probably the first question that needs to be answered. Is it in the IMDB data dumps? (We can't scrape IMDB.)

**Comment by luzer** [comment]
@BurntSushi thanks for the response. i searched the IMDB ftp and could find this info- so i believe its not possible.
thanks again
